scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8890']
    scrape_timeout: 60s
  - job_name: 'crowdsec'
    static_configs:
      - targets: ['crowdsec:6060']
    scrape_timeout: 60s
